import assert from 'node:assert/strict';
import fs from 'node:fs';
import { loadSourceDataset } from '../src/data-loaders/index.mjs';
import { loadUe5DungeonFramework, loadFirstMissionZoneTemplate, validateUe5DungeonFramework, ue5DungeonSummary, REQUIRED_STAGE_ORDER } from '../engine/unreal/ue5-dungeon-framework.mjs';

const framework = loadUe5DungeonFramework();
const template = loadFirstMissionZoneTemplate();
const dataset = loadSourceDataset({ includeMissions: true });
const sourceMission = dataset.missions.find(row => row.id === 'MG-F01-C01-M01');
const sourceFaction = JSON.parse(fs.readFileSync('data/factions.json', 'utf8')).find(row => row.id === 'MG-FACTION-001');
const validation = validateUe5DungeonFramework(framework, template, sourceMission, sourceFaction);
assert.equal(validation.ok, true, validation.issues.join('; '));
assert.equal(framework.primaryEngine, 'Unreal Engine 5');
assert.deepEqual(framework.aiGenerationStages, REQUIRED_STAGE_ORDER);
assert.equal(framework.deityScaleRules.standardCombatActiveAvatars, 1);
assert.equal(template.sourceMissionId, sourceMission.id);
assert.equal(template.sourceMissionTitle, sourceMission.title);
assert.equal(template.sourceMapId, sourceMission.mapId);
assert.ok(template.unrealRegion.theme.includes('Solar Dominion of Khepra'));
assert.ok(template.explorationZone.scaleLandmarks.length >= 4);
assert.ok(template.tacticalArena.combatRulesPreserved.includes('turn limit 11'));
assert.ok(template.bossArena.bossDesignNote.includes('no canonical boss'));
assert.ok(template.validationChecklist.mobilePerformance.includes('mobile lighting default'));
const summary = ue5DungeonSummary(framework, template);
assert.equal(summary.engine, 'Unreal Engine 5');
assert.equal(summary.firstMission, 'MG-F01-C01-M01');
assert.equal(summary.dataAssets, 5);
assert.equal(summary.blueprintActors, 6);
assert.equal(summary.dataTables, 7);
console.log(JSON.stringify({ ok: true, ue5DungeonFrameworkContract: 'PASS', summary }, null, 2));
